#!/bin/bash

# Currently just logging RAM usage
find ../benchmark_logs | grep "log$" | parallel "cat {} | grep 'Memory usage' -A 1 -B 11 | grep -e 'GB' -e 'INFO' | sed -r 's/^\[([^]]*)\].*$/\1/' | sed -r 's/^\s+([0-9.]+) .* ([0-9.]+) .*$/\t\1\t\2THEHORROR/g' | tr -d '\n' | sed 's/THEHORROR/\n/g' > {/.}.tsv"
